-- SpoolSpot schema, migration 0001 (SPOOL-22).
-- SQLite dialect only (ADR-0004), so the same file runs on Node SQLite and on Cloudflare D1.
--
-- Rules this file enforces:
--   * every table has tenant_id; primary keys and foreign keys include it (ADR-0004);
--   * no weight, temperature, cost or per-print usage column (project rules);
--   * no virtual tables (no FTS5), so the export stays D1-compatible (SPOOL-149);
--   * the event table is append-only (ADR-0006).
--   * text CHECKs also refuse an embedded NUL byte (SQLite's length() and GLOB stop at the first NUL).
-- Do not edit this file after it has been applied anywhere: add a new numbered migration.

CREATE TABLE tenant_settings (
  tenant_id TEXT NOT NULL PRIMARY KEY CHECK (
    length(tenant_id) BETWEEN 1 AND 64 AND tenant_id NOT GLOB '*[^A-Za-z0-9._:-]*'
  ),
  -- ADR-0006: reorder thresholds per usage level, tenant-wide. Low is fixed at 1 spool.
  moderate_threshold INTEGER NOT NULL DEFAULT 2 CHECK (moderate_threshold BETWEEN 1 AND 1000),
  high_threshold INTEGER NOT NULL DEFAULT 3 CHECK (high_threshold BETWEEN 1 AND 1000),
  CHECK (high_threshold >= moderate_threshold),
  CHECK (instr(CAST(tenant_id AS BLOB), x'00') = 0)
) STRICT;

CREATE TABLE location (
  tenant_id TEXT NOT NULL REFERENCES tenant_settings (tenant_id),
  -- The seed's stable slug (or a UUID for locations created later): lowercase letters, digits, dots, hyphens.
  id TEXT NOT NULL CHECK (
    length(id) BETWEEN 1 AND 64
    AND id NOT GLOB '*[^a-z0-9.-]*'
    AND id NOT GLOB '[.-]*'
    AND id NOT GLOB '*[.-]'
    AND id NOT GLOB '*[.-][.-]*'
  ),
  name TEXT NOT NULL CHECK (length(name) BETWEEN 1 AND 80),
  type TEXT NOT NULL CHECK (
    type IN ('container', 'passive_storage', 'active_storage', 'active_use', 'clip_storage')
  ),
  parent TEXT,
  leaf INTEGER NOT NULL CHECK (leaf IN (0, 1)),
  capacity INTEGER CHECK (capacity IS NULL OR capacity BETWEEN 1 AND 10000),
  capacity_mode TEXT CHECK (capacity_mode IS NULL OR capacity_mode IN ('hard', 'soft')),
  prefers_manufacturer TEXT CHECK (
    prefers_manufacturer IS NULL OR length(prefers_manufacturer) BETWEEN 1 AND 80
  ),
  -- 12 random Crockford base32 characters, uppercase; carries no personal data (ADR-0001).
  tag_id TEXT CHECK (
    tag_id IS NULL OR (length(tag_id) = 12 AND tag_id NOT GLOB '*[^0-9A-HJKMNP-TV-Z]*')
  ),
  tag_source TEXT CHECK (tag_source IS NULL OR tag_source IN ('sticker', 'holder_post')),
  PRIMARY KEY (tenant_id, id),
  FOREIGN KEY (tenant_id, parent) REFERENCES location (tenant_id, id),
  UNIQUE (tenant_id, tag_id),
  CHECK (id <> parent),
  CHECK (leaf = (type <> 'container')),
  CHECK (
    type <> 'container'
    OR (capacity IS NULL AND capacity_mode IS NULL AND tag_id IS NULL AND tag_source IS NULL)
  ),
  CHECK (type = 'container' OR (capacity_mode IS NOT NULL AND tag_source IS NOT NULL)),
  CHECK (
    type <> 'active_use'
    OR (capacity = 1 AND capacity_mode = 'hard' AND tag_source = 'holder_post')
  ),
  CHECK (
    instr(CAST(id AS BLOB), x'00') = 0
    AND instr(CAST(name AS BLOB), x'00') = 0
    AND (parent IS NULL OR instr(CAST(parent AS BLOB), x'00') = 0)
    AND (prefers_manufacturer IS NULL OR instr(CAST(prefers_manufacturer AS BLOB), x'00') = 0)
    AND (tag_id IS NULL OR instr(CAST(tag_id AS BLOB), x'00') = 0)
  )
) STRICT;

-- A foreign key cannot say "the parent must be a container", so a trigger does.
CREATE TRIGGER location_parent_is_container_insert
BEFORE INSERT ON location
WHEN NEW.parent IS NOT NULL
BEGIN
  SELECT RAISE(ABORT, 'location parent must be a container')
  WHERE EXISTS (
    SELECT 1 FROM location p
    WHERE p.tenant_id = NEW.tenant_id AND p.id = NEW.parent AND p.leaf = 1
  );
END;

CREATE TRIGGER location_parent_is_container_update
BEFORE UPDATE OF parent, tenant_id ON location
WHEN NEW.parent IS NOT NULL
BEGIN
  SELECT RAISE(ABORT, 'location parent must be a container')
  WHERE EXISTS (
    SELECT 1 FROM location p
    WHERE p.tenant_id = NEW.tenant_id AND p.id = NEW.parent AND p.leaf = 1
  );
END;

-- A container that has children cannot become a leaf, and a leaf that holds stock or clips cannot
-- become a container.
CREATE TRIGGER location_type_change_keeps_tree_valid
BEFORE UPDATE OF type, leaf ON location
BEGIN
  SELECT RAISE(ABORT, 'a location with children must stay a container')
  WHERE NEW.leaf = 1 AND EXISTS (
    SELECT 1 FROM location c WHERE c.tenant_id = OLD.tenant_id AND c.parent = OLD.id
  );
  SELECT RAISE(ABORT, 'a location that holds stock or clips must stay a leaf')
  WHERE NEW.leaf = 0 AND (
    EXISTS (SELECT 1 FROM stock_line s WHERE s.tenant_id = OLD.tenant_id AND s.location_id = OLD.id)
    OR EXISTS (SELECT 1 FROM clip k WHERE k.tenant_id = OLD.tenant_id AND k.location_id = OLD.id)
  );
END;

-- A location cannot become its own ancestor.
CREATE TRIGGER location_parent_has_no_cycle
BEFORE UPDATE OF parent ON location
WHEN NEW.parent IS NOT NULL
BEGIN
  SELECT RAISE(ABORT, 'a location cannot be its own ancestor')
  WHERE EXISTS (
    WITH RECURSIVE ancestors (id) AS (
      SELECT NEW.parent
      UNION
      SELECT l.parent FROM location l JOIN ancestors a
        ON l.tenant_id = NEW.tenant_id AND l.id = a.id AND l.parent IS NOT NULL
    )
    SELECT 1 FROM ancestors WHERE id = NEW.id
  );
END;

-- A filament is manufacturer + type + colour (ADR-0006). Its spool kind comes from the clip catalog.
CREATE TABLE filament (
  tenant_id TEXT NOT NULL REFERENCES tenant_settings (tenant_id),
  id TEXT NOT NULL CHECK (length(id) = 36 AND id NOT GLOB '*[^0-9a-f-]*'),
  manufacturer TEXT NOT NULL CHECK (length(manufacturer) BETWEEN 1 AND 80),
  type TEXT NOT NULL CHECK (length(type) BETWEEN 1 AND 40),
  color TEXT NOT NULL CHECK (length(color) BETWEEN 1 AND 80),
  spool_kind TEXT NOT NULL CHECK (spool_kind IN ('refillable', 'disposable')),
  -- ADR-0006 reorder level: how heavily the filament is used. A tap-set drop-down, never a measurement.
  reorder_level TEXT NOT NULL DEFAULT 'moderate' CHECK (reorder_level IN ('low', 'moderate', 'high')),
  auto_level INTEGER NOT NULL DEFAULT 0 CHECK (auto_level IN (0, 1)),
  PRIMARY KEY (tenant_id, id),
  UNIQUE (tenant_id, manufacturer, type, color),
  CHECK (
    instr(CAST(manufacturer AS BLOB), x'00') = 0
    AND instr(CAST(type AS BLOB), x'00') = 0
    AND instr(CAST(color AS BLOB), x'00') = 0
  )
) STRICT;

-- Boxed or bagged stock: counts only, per filament, location and pack type.
CREATE TABLE stock_line (
  tenant_id TEXT NOT NULL REFERENCES tenant_settings (tenant_id),
  id TEXT NOT NULL CHECK (length(id) = 36 AND id NOT GLOB '*[^0-9a-f-]*'),
  filament_id TEXT NOT NULL,
  location_id TEXT NOT NULL,
  pack TEXT NOT NULL CHECK (pack IN ('spool', 'refill')),
  count INTEGER NOT NULL CHECK (count BETWEEN 0 AND 10000),
  PRIMARY KEY (tenant_id, id),
  FOREIGN KEY (tenant_id, filament_id) REFERENCES filament (tenant_id, id),
  FOREIGN KEY (tenant_id, location_id) REFERENCES location (tenant_id, id),
  UNIQUE (tenant_id, filament_id, location_id, pack)
) STRICT;

-- A refillable filament cannot be changed to disposable while refill packs exist.
CREATE TRIGGER filament_spool_kind_keeps_refill_valid
BEFORE UPDATE OF spool_kind ON filament
WHEN NEW.spool_kind <> 'refillable'
BEGIN
  SELECT RAISE(ABORT, 'refill packs exist for this filament')
  WHERE EXISTS (
    SELECT 1 FROM stock_line s
    WHERE s.tenant_id = OLD.tenant_id AND s.filament_id = OLD.id AND s.pack = 'refill'
  );
END;

-- Boxed stock and clips are placed at leaf locations only.
CREATE TRIGGER stock_line_location_is_leaf_insert
BEFORE INSERT ON stock_line
BEGIN
  SELECT RAISE(ABORT, 'stock lines belong at a leaf location')
  WHERE EXISTS (
    SELECT 1 FROM location l
    WHERE l.tenant_id = NEW.tenant_id AND l.id = NEW.location_id AND l.leaf = 0
  );
END;

CREATE TRIGGER stock_line_location_is_leaf_update
BEFORE UPDATE OF location_id, tenant_id ON stock_line
BEGIN
  SELECT RAISE(ABORT, 'stock lines belong at a leaf location')
  WHERE EXISTS (
    SELECT 1 FROM location l
    WHERE l.tenant_id = NEW.tenant_id AND l.id = NEW.location_id AND l.leaf = 0
  );
END;

-- Spec: a refill pack is only valid for a refillable filament.
CREATE TRIGGER stock_line_refill_needs_refillable_insert
BEFORE INSERT ON stock_line
WHEN NEW.pack = 'refill'
BEGIN
  SELECT RAISE(ABORT, 'refill packs are only valid for refillable filaments')
  WHERE NOT EXISTS (
    SELECT 1 FROM filament f
    WHERE f.tenant_id = NEW.tenant_id AND f.id = NEW.filament_id AND f.spool_kind = 'refillable'
  );
END;

CREATE TRIGGER stock_line_refill_needs_refillable_update
BEFORE UPDATE OF pack, filament_id, tenant_id ON stock_line
WHEN NEW.pack = 'refill'
BEGIN
  SELECT RAISE(ABORT, 'refill packs are only valid for refillable filaments')
  WHERE NOT EXISTS (
    SELECT 1 FROM filament f
    WHERE f.tenant_id = NEW.tenant_id AND f.id = NEW.filament_id AND f.spool_kind = 'refillable'
  );
END;

-- A clip is individual and tagged, and belongs to one filament for life. location_id is empty until placed.
CREATE TABLE clip (
  tenant_id TEXT NOT NULL REFERENCES tenant_settings (tenant_id),
  id TEXT NOT NULL CHECK (length(id) = 36 AND id NOT GLOB '*[^0-9a-f-]*'),
  tag_id TEXT NOT NULL CHECK (length(tag_id) = 12 AND tag_id NOT GLOB '*[^0-9A-HJKMNP-TV-Z]*'),
  filament_id TEXT NOT NULL,
  location_id TEXT,
  state TEXT NOT NULL CHECK (state IN ('on_spool', 'spool_empty', 'free')),
  PRIMARY KEY (tenant_id, id),
  FOREIGN KEY (tenant_id, filament_id) REFERENCES filament (tenant_id, id),
  FOREIGN KEY (tenant_id, location_id) REFERENCES location (tenant_id, id),
  UNIQUE (tenant_id, tag_id),
  CHECK (instr(CAST(tag_id AS BLOB), x'00') = 0)
) STRICT;

-- Append-only movement history (ADR-0006). No free text: only types, ids and a server timestamp.
CREATE TABLE event (
  tenant_id TEXT NOT NULL REFERENCES tenant_settings (tenant_id),
  id TEXT NOT NULL CHECK (length(id) = 36 AND id NOT GLOB '*[^0-9a-f-]*'),
  type TEXT NOT NULL CHECK (
    type IN ('intake', 'open', 'move', 'load', 'unload', 'empty', 'retire', 'refill')
  ),
  clip_id TEXT,
  filament_id TEXT,
  from_location_id TEXT,
  to_location_id TEXT,
  occurred_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
    CHECK (length(occurred_at) = 24 AND occurred_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  PRIMARY KEY (tenant_id, id),
  FOREIGN KEY (tenant_id, clip_id) REFERENCES clip (tenant_id, id),
  FOREIGN KEY (tenant_id, filament_id) REFERENCES filament (tenant_id, id),
  FOREIGN KEY (tenant_id, from_location_id) REFERENCES location (tenant_id, id),
  FOREIGN KEY (tenant_id, to_location_id) REFERENCES location (tenant_id, id)
) STRICT;

CREATE INDEX event_by_filament ON event (tenant_id, filament_id, occurred_at);

CREATE TRIGGER event_is_append_only_update
BEFORE UPDATE ON event
BEGIN
  SELECT RAISE(ABORT, 'event is append-only');
END;

CREATE TRIGGER event_is_append_only_delete
BEFORE DELETE ON event
BEGIN
  SELECT RAISE(ABORT, 'event is append-only');
END;
